<a href="https://colab.research.google.com/github/dsuryapriya17-coder/heightvsweightdataset_linearregression/blob/main/petrolconsumptiondataset_multilinearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
data=pd.read_csv('/content/petrol_consumption.csv')

In [4]:
data.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64
 2   Paved_Highways                48 non-null     int64
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64
dtypes: float64(2), int64(3)
memory usage: 2.0 KB

In [6]:
data.describe()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
count,48.000000,48.000000,48.000000,48.000000,48.000000
mean,7.668333,4241.833333,5565.416667,0.570333,576.770833
std,0.950770,573.623768,3491.507166,0.055470,111.885816
min,5.000000,3063.000000,431.000000,0.451000,344.000000
25%,7.000000,3739.000000,3110.250000,0.529750,509.500000
50%,7.500000,4298.000000,4735.500000,0.564500,568.500000
75%,8.125000,4578.750000,7156.000000,0.595250,632.750000
max,10.000000,5342.000000,17782.000000,0.724000,968.000000

In [9]:
X = data.drop(columns=['Petrol_Consumption'])
y = data['Petrol_Consumption']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [11]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [12]:
df_coefs = pd.DataFrame({'Coef':reg.coef_, 'X':X.columns})
df_coefs

          Coef                             X
0   -37.006693                    Petrol_tax
1    -0.064383                Average_income
2    -0.004588                Paved_Highways
3  1323.374236  Population_Driver_licence(%)

In [13]:
print(f'intercept: {reg.intercept_}')

intercept: 406.460029074364

In [14]:
len(reg.coef_)

4

In [15]:
y_pred = reg.predict(X_test)

In [16]:
df_pred = pd.DataFrame({'y_test':y_test, 'pred': y_pred})
df_pred

    y_test        pred
47     524  565.194696
16     603  594.553023
36     640  628.443742
43     591  566.592619
0      541  529.192613
4      410  545.122295
26     577  588.851701
11     471  428.568328
2      561  584.838768
28     574  558.416002

In [19]:
print(f"Mean Absolute Error is: {metrics.mean_absolute_error(y_test, y_pred)}")
print(f"Root Mean Square Error is: {np.sqrt(metrics.mean_squared_error(y_test, y_pred))}")

Mean Absolute Error is: 32.62411316097338
Root Mean Square Error is: 48.62831282920479